user:
  outputs:
    default:
      account: NQPFLYN-RG91674
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: SYNOVATE_DB
      password: Fan00huan1989!
      retry_on_database_errors: true
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 6
      type: snowflake
      user: FANHUAN1989
      warehouse: COMPUTE_WH
  target: default
