{{ config(materialized='table') }}
WITH CUSTOMERORDERS AS (
    SELECT C.CUSTOMERID,
           CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME,
           COUNT(O.ORDERID) AS NO_OF_ORDER
    FROM RAW.CUSTOMERS C
    JOIN RAW.ORDERS O
      ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY C.CUSTOMERID, CUSTOMERNAME
    ORDER BY NO_OF_ORDER DESC
)

SELECT  CUSTOMERID, CUSTOMERNAME, NO_OF_ORDER FROM  CUSTOMERORDERS