{{ config(materialized='table') }}

WITH CUSTOMERREVENUE AS (
    SELECT C.CUSTOMERID,
           CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME,
           COUNT(DISTINCT O.ORDERID) AS ORDERCOUNT,
           SUM(OI.QUANTITY * OI.UNITPRICE) AS REVENUE
    FROM RAW.CUSTOMERS C
    JOIN RAW.ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
    JOIN RAW.ORDERITEMS OI ON O.ORDERID = OI.ORDERID
    GROUP BY C.CUSTOMERID, CUSTOMERNAME
    ORDER BY REVENUE DESC)

SELECT CUSTOMERID, CUSTOMERNAME, ORDERCOUNT, REVENUE FROM  CUSTOMERREVENUE